Make sure for BlankOn add dotovr to sambashare group

diff --git a/debian/samba.postinst b/debian/samba.postinst
--- a/debian/samba.postinst
+++ b/debian/samba.postinst
@@ -34,7 +34,7 @@ if dpkg --compare-versions "$2" lt-nl 2:3.6.15-2; then
 	fi
 
 	# Remove NetBIOS entries from /etc/inetd.conf
-	if [ -x /usr/sbin/update-inetd ]; then
+	if [ -x "`which update-inetd 2>/dev/null`" ]; then
 		update-inetd --remove netbios-ssn
 	fi
 fi
@@ -45,6 +45,12 @@ if dpkg --compare-versions "$2" lt-nl 2:4.0.12+dfsg-2~; then
 	fi
 fi
 
+if dpkg --compare-versions "$2" lt-nl 2:4.1.13+dfsg-2~; then
+	# on upgrades from wheezy to jessie, the samba init script should not stay
+	# active, see #766690
+	update-rc.d samba remove
+fi
+
 # add the sambashare group
 if ! getent group sambashare > /dev/null 2>&1
 then
@@ -53,11 +59,11 @@ then
 	# initial users for this group; Debian has no equivalent group,
 	# so leaving the sambashare group empty is the more secure default
 	if [ -x "`which lsb_release 2>/dev/null`" ] \
-	   && [ "`lsb_release -s -i`" = "Ubuntu" ]
+	   && [ "`lsb_release -s -i`" = "Blankon" ]
 	then
 		OLDIFS="$IFS"
 		IFS=","
-		for USER in `getent group admin | cut -f4 -d:`; do
+		for USER in `getent group sambashare | cut -f4 -d:`; do
 			adduser "$USER" sambashare \
 			|| ! getent passwd "$USER" >/dev/null
 		done
@@ -68,6 +74,26 @@ fi
 if [ ! -e /var/lib/samba/usershares ]
 then
 	install -d -m 1770 -g sambashare /var/lib/samba/usershares
+fi
+
+# mimic source4/smbd/server.c and mask service before it fails
+SERVER_ROLE=`samba-tool testparm --parameter-name="server role"  2>/dev/null | tail -1`
+SERVER_SERVICES=`samba-tool testparm --parameter-name="server services"  2>/dev/null | tail -1`
+DCERPC_ENDPOINT_SERVERS=`samba-tool testparm --parameter-name="dcerpc endpoint servers"  2>/dev/null | tail -1`
+if [ "$SERVER_ROLE" != "active directory domain controller" ] \
+	&& ( echo "$SERVER_SERVICES" | grep -qv '\(^\|, \)smb\(,\|$\)' ) \
+	&& ( echo "$DCERPC_ENDPOINT_SERVERS" | grep -qv '\(^\|, \)remote\(,\|$\)' ) \
+	&& ( echo "$DCERPC_ENDPOINT_SERVERS" | grep -qv '\(^\|, \)mapiproxy\(,\|$\)' ) \
+; then
+    if [ ! -e /etc/systemd/system/samba-ad-dc.service ]; then
+        mkdir -p /etc/systemd/system
+        ln -s /dev/null /etc/systemd/system/samba-ad-dc.service
+        # In case this system is running systemd, we make systemd reload the unit files
+        # to pick up changes.
+        if [ -d /run/systemd/system ] ; then
+            systemctl --system daemon-reload >/dev/null || true
+        fi
+	fi
 fi
 
 #DEBHELPER#
